version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: H@a123456789
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
