// <auto-generated />
using System;
using H5D_Delivery.Mgmt.Backend.Delivery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H5D_Delivery.Mgmt.Backend.Migrations.Delivery
{
    [DbContext(typeof(DeliveryContext))]
    [Migration("20230605120148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Customer.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedRobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DeliveryOrder", (string)null);
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPlan", (string)null);
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizationKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeliveryPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlannedDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RealDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StepSequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPlanId");

                    b.ToTable("DeliveryStep", (string)null);
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Order.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorizationKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeliveryOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeliveryOrderId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarliestDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("DeliveryOrderId1");

                    b.HasIndex("ProductId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Product.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryOrder", b =>
                {
                    b.HasOne("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryPlan", "DeliveryPlan")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPlan");
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryStep", b =>
                {
                    b.HasOne("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryPlan", null)
                        .WithMany("DeliverySteps")
                        .HasForeignKey("DeliveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("H5D_Delivery.Mgmt.Backend.Delivery.Domain.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("DeliveryStepId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("DeliveryStepId");

                            b1.ToTable("DeliveryStep");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryStepId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Order.Domain.Order", b =>
                {
                    b.HasOne("H5D_Delivery.Mgmt.Backend.Customer.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryOrder", null)
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryOrderId");

                    b.HasOne("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryOrder", "DeliveryOrder")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId1");

                    b.HasOne("H5D_Delivery.Mgmt.Backend.Product.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveryOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("H5D_Delivery.Mgmt.Backend.Delivery.Domain.DeliveryPlan", b =>
                {
                    b.Navigation("DeliverySteps");
                });
#pragma warning restore 612, 618
        }
    }
}
